### ISSUE TITLE
FileAdapter does not properly close FileIO resources

### ISSUE THREAD

**Issue by stevendlander** [dashea/requests-file#15]
When opening local files using the FileAdapter in requests, the following `ResourceWarning` is thrown during unit tests:

```
ResourceWarning: unclosed file <_io.FileIO name='/Users/my_user/Projects/my_project/path/to/my/data/big_data_list.dat' mode='rb' closefd=True>
```
This is happening on Python 3.7.4 interpreter.  Converting the [response object](https://github.com/dashea/requests-file/blob/master/requests_file.py#L31) to an instance variable, and then calling `self._resp.raw.close()` within the [FileAdapter.close()](https://github.com/dashea/requests-file/blob/master/requests_file.py#L109) method resolves this problem.

I can submit a pull request, if needed.

**Comment by dashea** [comment]
`resp` can't be converted to an instance variable, since the adapter is used for all file:// requests, so if it's used for multiple requests then there will be multiple response objects. `FileAdapter.close()` doesn't do anything since there's nothing allocated local to the `FileAdapter` itself. `HttpAdapter` has some adapter-specific data for connection pool management, for instance.

Can you add an explicit `resp.close()` to your tests, or use the response object as a context manager?

**Comment by dashea** [comment]
I'm going to close this one since I don't think it's a bug in requests-file. Let me know if there are there any changes that need to be made in this library. Thanks!
