### ISSUE TITLE
Use requests-file on windows (automatically created file paths)

### ISSUE THREAD

**Issue by LeKono** [dashea/requests-file#5]
Hey guys, 

I am building paths in my test files automaticaly using `os.sep`. If I build paths to files they are created with a `\`. Later in the code I use the `FileAdapter`. The problem here is: It decodes all paths with `/` so the automatically created windows paths will not be decoded propperly and raise an Exception.

Regards,
Kono

**Comment by cthoyt** [comment]
Is the offending line here https://github.com/dashea/requests-file/blob/master/requests_file.py#L39? Maybe just a normalization of `url_parts` then replacement with `os.sep` would do the trick

Also, do paths like `file:///path/to/file` work on windows? Maybe the best work-around in the tests is to use one of the other path normalization modules like `os.path.abspath` or something from `ntpath` in your tests rather than changing the way requests-file works

Also see pybel/pybel#42

**Comment by dashea** [comment]
Windows uses / as the path separator in file: URLs. You need to encode your paths as as URL using something like urllib.pathname2url (in 2.x, urllib.request.pathname2url in 3.x).

**Comment by jaraco** [comment]
I ran into this issue today. It might be worthwhile adding a one or two line note to the readme advising users that they likely will want to wrap their file paths in `pathname2url` and 'abspath` in order to be compatible with URL constraints.
